"""Ephemeral inbound shared-content transfer state.

The Mac sends one approved manifest followed by bounded chunks.  This module
owns ordering, digests, quotas, approval and cleanup; it does not persist
bytes or expose a file path to a provider.  A transport adapter can therefore
feed both the WebRTC and WebSocket paths into the same state machine.
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace
from hashlib import sha256
import base64
import inspect
import uuid
from typing import Any

from jarvis.bot.shared_content import (
    MAX_ATTACHMENTS,
    MAX_CHUNK_BYTES,
    MAX_IMAGE_BYTES,
    MAX_QUESTION_CHARS,
    SharedContentService,
    normalize_shared_content,
    validate_input_message,
)
from jarvis.bot.sensitive_turn import SensitiveTurn


@dataclass
class _Attachment:
    content_id: str
    kind: str
    mime_type: str
    digest: str
    total_bytes: int
    chunks: bytearray = field(default_factory=bytearray)
    next_sequence: int = 0
    committed: bool = False


class SharedContentTransferSession:
    """Validate and consume one user-approved transfer batch.

    Instances are session-scoped.  ``close`` drops all decoded and encoded
    bytes, and every terminal path calls it.  Duplicate request IDs are
    replayed by the service, while duplicate chunks are rejected rather than
    silently appended twice.
    """

    def __init__(self, service: SharedContentService, *, session_id: str | None = None,
                 generation: str | None = None,
                 sensitive_turn: SensitiveTurn | None = None):
        self.service = service
        self.session_id = session_id
        self.generation = generation
        self.sensitive_turn = sensitive_turn
        self.batch_id: str | None = None
        self.transfer_id: str | None = None
        self.approval_id: str | None = None
        self.question: str | None = None
        self.profile: dict[str, str] = {}
        self._attachments: dict[str, _Attachment] = {}
        self._analysis_request_id: str | None = None
        self._closed = False

    def _check_session(self, message: dict[str, Any]) -> None:
        for name, expected in (("session_id", self.session_id), ("generation", self.generation)):
            if expected is not None and message.get(name) != expected:
                raise ValueError("stale input session")

    def _status(self, message: dict[str, Any], status: str, code: str, summary: str,
                *, message_type: str = "input/status", **extra: Any) -> dict[str, Any]:
        result: dict[str, Any] = {
            "type": message_type, "version": 1,
            "status": status, "code": code, "summary": summary[:240],
        }
        for key in ("session_id", "generation"):
            if key in message:
                result[key] = message[key]
        for key in ("request_id", "batch_id", "transfer_id", "attachment_id"):
            if key in message:
                result[key] = message[key]
        result.update(extra)
        return result

    def handle(self, message: dict[str, Any]) -> dict[str, Any]:
        """Synchronously consume a protocol message and return a status."""
        try:
            normalized = validate_input_message(message)
            if not normalized.get("request_id"):
                raise ValueError("input request id is required")
            self._check_session(normalized)
            kind = normalized["type"]
            if kind == "input/manifest":
                return self._manifest(normalized)
            if kind == "input/chunk":
                return self._chunk(normalized)
            if kind == "input/commit":
                return self._commit(normalized)
            if kind == "input/cancel":
                if self._analysis_request_id:
                    self.service.cancel(self._analysis_request_id)
                self.close()
                return self._status(normalized, "cancelled", "cancelled", "Shared content cancelled.")
            if kind == "input/analyze":
                return self._analyze_request(normalized)
            # Offers are generated by the voice tool and are intentionally not
            # accepted as approval from the network client. Treating a
            # server-only offer as an approval would let a forged client
            # message bypass the explicit manifest/approval boundary.
            return self._status(normalized, "error", "server_only_message",
                                "That input message is server-only.")
        except ValueError as exc:
            return self._status(message if isinstance(message, dict) else {}, "error",
                                "invalid_input", str(exc))

    def _manifest(self, message: dict[str, Any]) -> dict[str, Any]:
        if self._attachments and message["batch_id"] != self.batch_id:
            return self._status(message, "error", "transfer_in_progress",
                                "Another shared-content transfer is already in progress.")
        attachments = message["attachments"]
        if len(attachments) > MAX_ATTACHMENTS:
            raise ValueError("too many attachments")
        parsed: dict[str, _Attachment] = {}
        for item in attachments:
            content_id = item["content_id"]
            total = item["total_bytes"]
            if item["kind"] == "image" and total > MAX_IMAGE_BYTES:
                raise ValueError("image content exceeds quota")
            if total < 1:
                raise ValueError("attachment is empty")
            if content_id in parsed:
                raise ValueError("duplicate attachment id")
            parsed[content_id] = _Attachment(content_id, item["kind"], item["mime_type"],
                                             item["digest"], total)
        self.batch_id = message["batch_id"]
        self.transfer_id = str(uuid.uuid4())
        self.approval_id = message["approval_id"]
        if self.sensitive_turn is not None:
            # Arm only after the manifest has passed every quota/digest
            # metadata check. Staging or malformed input never changes the
            # ordinary conversation's memory behavior.
            self.sensitive_turn.arm_temporary_content()
        self.question = str(message.get("question", self.question or ""))[:MAX_QUESTION_CHARS]
        self._attachments = parsed
        self._closed = False
        return self._status(message, "ok", "transfer_accepted", "Approved content manifest accepted.",
                            message_type="input/accept", transfer_id=self.transfer_id,
                            temporary_content_mode=True, max_chunk_bytes=MAX_CHUNK_BYTES,
                            attachment_count=len(parsed))

    def _attachment(self, message: dict[str, Any]) -> _Attachment:
        if not self.batch_id or message.get("transfer_id") != self.transfer_id:
            raise ValueError("unknown transfer")
        item = self._attachments.get(message["attachment_id"])
        if item is None:
            raise ValueError("unknown attachment")
        return item

    def _chunk(self, message: dict[str, Any]) -> dict[str, Any]:
        item = self._attachment(message)
        if item.committed:
            return self._status(message, "error", "already_committed", "Attachment is already committed.")
        if message["sequence"] != item.next_sequence:
            raise ValueError("chunk sequence is not the next expected sequence")
        raw = base64.b64decode(message["base64"], validate=True)
        if len(raw) > MAX_CHUNK_BYTES:
            raise ValueError("chunk exceeds quota")
        if len(item.chunks) + len(raw) > item.total_bytes:
            raise ValueError("chunk bytes exceed manifest")
        item.chunks.extend(raw)
        item.next_sequence += 1
        return self._status(message, "ok", "chunk_ack", "Content chunk accepted.",
                            message_type="input/ack", sequence=item.next_sequence - 1)

    def _commit(self, message: dict[str, Any]) -> dict[str, Any]:
        item = self._attachment(message)
        if item.committed:
            return self._status(message, "noop", "already_committed", "Attachment was already committed.")
        if message["total_chunks"] != item.next_sequence or message["total_bytes"] != len(item.chunks):
            raise ValueError("commit totals do not match received chunks")
        if sha256(item.chunks).hexdigest() != message["sha256"] or message["sha256"] != item.digest:
            raise ValueError("content digest does not match manifest")
        try:
            if item.kind == "text":
                content = normalize_shared_content(kind="text", text=bytes(item.chunks).decode("utf-8"),
                                                    mime_type=item.mime_type)
            else:
                content = normalize_shared_content(kind="image", data=bytes(item.chunks),
                                                   mime_type=item.mime_type)
        except (UnicodeDecodeError, ValueError) as exc:
            raise ValueError(f"attachment rejected: {exc}") from exc
        # Preserve the client-assigned identity so the later analyze request
        # addresses the exact approved item rather than a new UUID generated
        # by local normalization.
        self.service.stage(replace(content, content_id=item.content_id))
        item.committed = True
        # The staged object is owned by the service until analyze/cancel; the
        # transfer buffer can be dropped immediately to cap peak memory.
        item.chunks.clear()
        all_committed = all(candidate.committed for candidate in self._attachments.values())
        return self._status(message, "ok", "ready" if all_committed else "attachment_committed",
                            "Approved content is ready for analysis." if all_committed
                            else "Attachment committed for analysis.",
                            message_type="input/ready" if all_committed else "input/status",
                            batch_id=self.batch_id, transfer_id=self.transfer_id)

    def _analyze_request(self, message: dict[str, Any]) -> dict[str, Any]:
        if not self.batch_id or message["batch_id"] != self.batch_id or not self.approval_id:
            raise ValueError("no approved batch")
        if message["attachment_ids"] != list(self._attachments):
            # Reordering is safe, but the set must be exactly the approved set.
            if set(message["attachment_ids"]) != set(self._attachments):
                raise ValueError("analysis attachments do not match approval")
        if not all(item.committed for item in self._attachments.values()):
            raise ValueError("all attachments must be committed before analysis")
        question = message["question"]
        if self.question and question != self.question:
            raise ValueError("analysis question does not match approval")
        return self._status(message, "ok", "ready_for_analysis", "Approved content is ready for analysis.")

    async def analyze(self, message: dict[str, Any]) -> dict[str, Any]:
        """Run the approved analysis and clear ephemeral state afterward."""
        try:
            normalized = validate_input_message(message)
            if not normalized.get("request_id"):
                raise ValueError("input request id is required")
            self._check_session(normalized)
            ready = self._analyze_request(normalized)
        except ValueError as exc:
            return self._status(message if isinstance(message, dict) else {}, "error",
                                "invalid_input", str(exc))
        if ready["status"] != "ok":
            return ready
        message = normalized
        self._analysis_request_id = message.get("request_id", "")
        try:
            result = self.service.analyze(
                message["request_id"], message["batch_id"],
                list(message["attachment_ids"]), message["question"], self.approval_id,
            )
            if inspect.isawaitable(result):
                result = await result
            return self._status(message, "ok" if result.get("ok") else "error",
                                "analysis_complete" if result.get("ok") else result.get("error_code", "analysis_failed"),
                                "Shared content analysis complete." if result.get("ok") else "Shared content analysis failed.",
                                data=result)
        finally:
            self._analysis_request_id = None
            self.close()

    def close(self) -> None:
        for item in self._attachments.values():
            item.chunks.clear()
        self._attachments.clear()
        if self._analysis_request_id:
            self.service.cancel(self._analysis_request_id)
        self.batch_id = self.approval_id = self.question = None
        self.transfer_id = None
        self.profile = {}
        self._closed = True
